### ISSUE TITLE
Hack the Budget name & Branding

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/hack-the-budget#9]
- Is this the best name for an app? The word "hack" can have a negative connotation for the general public. I propose we spend some time post Aug 16 event thinking about the branding of this app that is friendly and accessible for the "general public"

**Comment by graceatkins** [comment]
Maybe a play on words on Fund or just go off of budget game night idea and just say Austin Budget Game

**Comment by graceatkins** [comment]
out of the box budgeting?

**Comment by brainnews** [comment]
I like the sentiment behind "out of the box" because it speaks to the idea of shifting or remixing things in order to possibly make them better. Is that what we want people to walk away with after playing with the app? We should figure that out first and then brainstorm around that idea to come to a pithy/accessible name that describes the feeling we want people have while playing it.

**Comment by graceatkins** [comment]
I like the out of the box idea for the same reasons. I think we want people
to rethink their thoughts about how the city budget works and how their
engagement around it works. I am happy to talk/meet anytime to discuss
more!

**Comment by VictoriaODell** [comment]
We're going with a Build a Budget for now~
Similar to hack but less devy
